---
name: Autorelease
on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled
      - closed

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create new tag
        uses: projectsyn/pr-label-tag-action@v1
        with:
          trigger: |
            Release
